#! /usr/bin/env bash

ASSEMBLY='/home/afaren/twars/assembly'
USAGE="Usage: `basename $0` < start | stop > container names"
ERR_MSG="the ASSEMBLY directory you setup is not exist!"

if [[ $# -eq 0 ]]; then
	echo "$USAGE" >&2 
	exit 1
fi

if [[ ! -d $ASSEMBLY ]]; then
	echo "$ERR_MSG" >&2
	exit 1
fi

cd $ASSEMBLY 

start() {
	docker-compose -f docker-compose-dev.yml up -d $*
}

stop() {
	docker-compose -f docker-compose-dev.yml kill $*
}

action="${1}"


case $action in
	start) 
		echo "start"
		shift
		start "$*"
		;;
	 stop)
		echo "stop"
		shift
		stop "$*"
		;;
		*)
		echo "start | stop" 
		;;
esac
