#! /usr/bin/env bash

ASSEMBLY='/home/afaren/twars/assembly'

cd $ASSEMBLY 

start() {
	docker-compose up -d $*
}

stop() {
	docker-compose kill $*
}

action="${1}"


case $action in
	start) 
		echo "start"
		shift
		start "$*"
		;;
	 stop)
		echo "stop"
		shift
		stop "$*"
		;;
		*)
		echo "start | stop" 
		;;
esac
